import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import os


# ----------------------------------------------------------------------------------# 

# Capstone College ROI Project prepare file (prepare.py) #

''' This file:
    
    Divides complete uncleaned df into 3 separate dfs:
    
    1. roi_df = Financial Cost Features needed for ROI Target Variable
    
    2. general_df = All qualitative and addl. data proposed for further exploration
    
    3. loan_df = All pertinent loan data (most likely used for Tableau Dashboard deliverable)

    '''

# ----------------------------------------------------------------------------------# 


def roi_df(df):
    roi_df = df[
        'MD_EARN_1YR',
        'MD_EARN_2YR',
        'MD_EARN_3YR',
        'NPT4_PUB',
        'NPT4_PRIV',
        'NPT4_PROG',
        'NPT4_OTHER',
        'COSTT4_A',
        'COSTT4_P',
        'TUITIONFEE_IN',
        'TUITIONFEE_OUT',
        'PCTPELL',
        'PCTFLOAN',
        'BOOKSUPPLY',
        'ROOMBOARD_ON',
        'OTHEREXPENSE_ON',
        'ROOMBOARD_OFF',
        'OTHEREXPENSE_OFF',
        'OTHEREXPENSE_FAM'
        ]

def general_df(df):
    general_df = df[
        'UNITID',
        'INSTNM',
        'CITY',
        'STABBR',
        'ZIP',
        'REGION',
        'CIPCODE',
        'CIPDESC',
        'CREDLEV',
        'CREDDESC',
        'ACCREDAGENCY',
        'NUMBRANCH',
        'SCH_DEG',
        'PREDDEG',
        'CCBASIC',
        'CCUGPROF',
        'CCSIZSET',
        'HBCU',
        'DISTANCEONLY',
        'OPEFLAG',
        'ADM_RATE', 
        'ADMCON7',
        'SAT_AVG', 
        'ACTCMMID',
        'UGDS_WHITE',
        'UGDS_BLACK',
        'UGDS_HISP',
        'UGDS_ASIAN',
        'UGDS_AIAN',
        'UGDS_NHPI',
        'UGDS_2MOR',
        'UGDS_NRA',
        'UGDS_UNKN',
        'UGDS_WHITENH',
        'UGDS_BLACKNH',
        'UGDS_API',
        'UGDS_AIANOLD',
        'C150_4_WHITE',
        'C150_4_BLACK',
        'C150_4_HISP',
        'C150_4_ASIAN',
        'C150_4_AIAN',
        'C150_4_NHPI',
        'C150_4_2MOR',
        'C150_4_NRA',
        'C150_4_UNKN',
        'C150_4_WHITENH',
        'C150_4_BLACKNH',
        'C150_4_API',
        'C150_4_AIANOLD',
        'C150_4_HISPOLD',
        'PCIP01',
        'PCIP03',
        'PCIP04',
        'PCIP05',
        'PCIP09',
        'PCIP10',
        'PCIP11',
        'PCIP12',
        'PCIP13',
        'PCIP14',
        'PCIP15',
        'PCIP16',
        'PCIP19',
        'PCIP22',
        'PCIP23',
        'PCIP24',
        'PCIP25',
        'PCIP26',
        'PCIP27',
        'PCIP29',
        'PCIP30',
        'PCIP31',
        'PCIP38',
        'PCIP39',
        'PCIP40',
        'PCIP41',
        'PCIP42',
        'PCIP43',
        'PCIP44',
        'PCIP45',
        'PCIP46',
        'PCIP47',
        'PCIP48',
        'PCIP49',
        'PCIP50',
        'PCIP51',
        'PCIP52',
        'PCIP54',
        'PPTUG_EF',
        'NUM4_PUB',
        'NUM4_PRIV',
        'NUM4_PROG',
        'NUM4_OTHER',
        'AVGFACSAL',
        'C150_4',
        'C150_L4',
        'PFTFTUG1_EF',
        'RET_FT4',
        'RET_FTL4',
        'RET_PT4',
        'RET_PTL4',
        'PAR_ED_PCT_1STGEN',
        'FEMALE',
        'MARRIED',
        'DEPENDENT',
        'VETERAN',
        'FIRST_GEN',
        'FAMINC',
        'MD_FAMINC',
        'D_PCTPELL_PCTFLOAN',
        'UGNONDS',
        'GRADS',
        'PRGMOFR'
    ]


def loan_df(df):
    loan_df = df[
        'COUNT_ED',
        'LOAN_EVER',
        'PELL_EVER',
        'FTFTPCTPELL',
        'FTFTPCTFLOAN',
        'RPY_1YR_RT',
        'COMPL_RPY_1YR_RT',
        'NONCOM_RPY_1YR_RT',
        'LO_INC_RPY_1YR_RT',
        'MD_INC_RPY_1YR_RT',
        'HI_INC_RPY_1YR_RT',
        'DEP_RPY_1YR_RT',
        'IND_RPY_1YR_RT',
        'PELL_RPY_1YR_RT',
        'NOPELL_RPY_1YR_RT',
        'FEMALE_RPY_1YR_RT',
        'MALE_RPY_1YR_RT',
        'FIRSTGEN_RPY_1YR_RT',
        'NOTFIRSTGEN_RPY_1YR_RT',
        'RPY_3YR_RT',
        'COMPL_RPY_3YR_RT',
        'NONCOM_RPY_3YR_RT',
        'LO_INC_RPY_3YR_RT',
        'MD_INC_RPY_3YR_RT',
        'HI_INC_RPY_3YR_RT',
        'DEP_RPY_3YR_RT',
        'IND_RPY_3YR_RT',
        'PELL_RPY_3YR_RT',
        'NOPELL_RPY_3YR_RT',
        'FEMALE_RPY_3YR_RT',
        'MALE_RPY_3YR_RT',
        'FIRSTGEN_RPY_3YR_RT',
        'NOTFIRSTGEN_RPY_3YR_RT',
        'RPY_5YR_RT',
        'COMPL_RPY_5YR_RT',
        'NONCOM_RPY_5YR_RT',
        'LO_INC_RPY_5YR_RT',
        'MD_INC_RPY_5YR_RT',
        'HI_INC_RPY_5YR_RT',
        'DEP_RPY_5YR_RT',
        'IND_RPY_5YR_RT',
        'PELL_RPY_5YR_RT',
        'NOPELL_RPY_5YR_RT',
        'FEMALE_RPY_5YR_RT',
        'MALE_RPY_5YR_RT',
        'FIRSTGEN_RPY_5YR_RT',
        'NOTFIRSTGEN_RPY_5YR_RT',
        'RPY_7YR_RT',
        'COMPL_RPY_7YR_RT',
        'NONCOM_RPY_7YR_RT',
        'LO_INC_RPY_7YR_RT',
        'MD_INC_RPY_7YR_RT',
        'HI_INC_RPY_7YR_RT',
        'DEP_RPY_7YR_RT',
        'IND_RPY_7YR_RT',
        'PELL_RPY_7YR_RT',
        'NOPELL_RPY_7YR_RT',
        'FEMALE_RPY_7YR_RT',
        'MALE_RPY_7YR_RT',
        'FIRSTGEN_RPY_7YR_RT',
        'NOTFIRSTGEN_RPY_7YR_RT',
        'DEBT_MDN',
        'GRAD_DEBT_MDN',
        'WDRAW_DEBT_MDN',
        'LO_INC_DEBT_MDN',
        'MD_INC_DEBT_MDN',
        'HI_INC_DEBT_MDN',
        'DEP_DEBT_MDN',
        'IND_DEBT_MDN',
        'PELL_DEBT_MDN',
        'NOPELL_DEBT_MDN',
        'FEMALE_DEBT_MDN',
        'MALE_DEBT_MDN',
        'FIRSTGEN_DEBT_MDN',
        'NOTFIRSTGEN_DEBT_MDN',
        'CUML_DEBT_N',
        'CUML_DEBT_P90',
        'CUML_DEBT_P75',
        'CUML_DEBT_P25',
        'CUML_DEBT_P10',
        'P_DEBT_ALL_PP_EVAL_MEAN',
        'P_DEBT_ALL_PP_EVAL_MDN',
        'P_DEBT_PELL_PP_EVAL_MEAN',
        'P_DEBT_PELL_PP_EVAL_MDN',
        'P_DEBT_ALL_STGP_EVAL_MEAN',
        'P_DEBT_ALL_STGP_EVAL_MDN', 
        'P_DEBT_PELL_STGP_EVAL_MEAN',
        'P_DEBT_PELL_STGP_EVAL_MDN',
        'P_DEBT_NOPELL_STGP_EVAL_MEAN',
        'P_DEBT_NOPELL_STGP_EVAL_MDN',
        'P_DEBT_ALL_PP_EVAL_MDN10YRPAY',
        'P_DEBT_ALL_STGP_EVAL_MDN10YRPAY'
    ]


# ----------------------------------------------------------------------------------# 

